### PR TITLE
APT-619 changing radar modes

### PR DESCRIPTION
**Pull request by iurii-provizio**
https://provizio.atlassian.net/browse/APT-619

### CODE REVIEW

**Review by psilar — COMMENTED** [review]
Code looks good - compiles clean and all tests passing.  I don't understand the point of provizio_wait_for_radar_mode_change() though.  What's the need for this function/callback if the radar_mode is to be included in the header of point_cloud packets?

**Comment by iurii-provizio** [comment]
> Code looks good - compiles clean and all tests passing. I don't understand the point of provizio_wait_for_radar_mode_change() though. What's the need for this function/callback if the radar_mode is to be included in the header of point_cloud packets?

It's due to the standard (one of) use logic I anticipate (may use it in APT GUI, but maybe not - we'll see):
1. My system operates normally with point clouds coming from a radar (or radars)
2. Due to some event, like ego velocity change or moving from a motorway to a city, I want to change a radar mode and make sure my code now operates with the new mode.
3. I close an existent connection and stop its receive loop.
4. I set the new mode
5. I make sure it's been applied by calling that `provizio_wait_for_radar_mode_change` and even probably retrying #4 if it didn't happen in time - given UDP may sometimes loose packets.
6. When I know the radar operates in the new mode, I go back to 1.

I.e. it follows the simplest linear logic, that may often be very useful. In the same time, it doesn't have to be used, and after requesting the new mode you may just keep doing what you were, the radar mode will change at some point (unless it doesn't due to a lost UDP packet, but it should be a very rare thing in local networks).

**Comment by psilar** [comment]
@iurii-provizio would it not be simpler logic to process UDP packets in a loop and hand off the point clouds to a suitable handler based on the mode, e.g. something like

```
while(receive_udp_point_cloud_packet_blocking(packet)) {
  if(packet->radar_mode == foo) {
    handle_foo_point_cloud();
  }
  else if(packet->radar_mode == bar) {
    handle_bar_point_cloud();
  }
}

```
This saves on having to close and re-open the socket, and would allow the system to keep processing "old" `radar_mode` point clouds until the new `radar_mode` becomes active.  Alternatively, the logic could check for `packet->radar_mode == expected_mode` and ignore packets until the `expected_mode` becomes active (or timeout and retry changing modes).

This seems a more suitable / intuitive design pattern though I'll defer to your judgement on this as I'm unfamiliar with the implementation details of apt_gui.

Btw, do you expect radar_mode to be divided into bit-fields such that it can represent multiple radar configuration aspects or will it be exclusively used for radar range?

**Comment by iurii-provizio** [comment]
> @iurii-provizio would it not be simpler logic to process UDP packets in a loop and hand off the point clouds to a suitable handler based on the mode, e.g. something like
> 
> ```
> while(receive_udp_point_cloud_packet_blocking(packet)) {
>   if(packet->radar_mode == foo) {
>     handle_foo_point_cloud();
>   }
>   else if(packet->radar_mode == bar) {
>     handle_bar_point_cloud();
>   }
> }
> ```
> 
> This saves on having to close and re-open the socket, and would allow the system to keep processing "old" `radar_mode` point clouds until the new `radar_mode` becomes active. Alternatively, the logic could check for `packet->radar_mode == expected_mode` and ignore packets until the `expected_mode` becomes active (or timeout and retry changing modes).
> 
> This seems a more suitable / intuitive design pattern though I'll defer to your judgement on this as I'm unfamiliar with the implementation details of apt_gui.
> 
> Btw, do you expect radar_mode to be divided into bit-fields such that it can represent multiple radar configuration aspects or will it be exclusively used for radar range?

I changed now the way we validate mode changes, done safer and more conveniently. Also updated documentation. Please re-review.

**Review by psilar — APPROVED** [review]
Looks good.  I much prefer the simplified API - a blocking call with a timeout is easy to grok (KISS).  If customers want anything more complicated that can be left up to them.

**Pull request merged**
